Added numpy<1.25 to req, updated README
Somehow, numpy 1.25 changed something that broke the tests:
They would fail with an import error INSIDE numpy source
```
/opt/miniconda3/envs/rkhs2/lib/python3.9/site-packages/numpy/testing/overrides.py:8: in <module>
    import numpy.core.umath as _umath
E   ImportError: cannot import name 'umath' from '' (unknown location)
```
However, just `import numpy.core.umath as _umath` in the interpreter
does NOT fail, only if pytest is involved.
I could not find any explanations for it and I don't care anymnore,
a workaround is requiring a low enough version of numpy, or not using
pytest.